### PR TITLE
Survey UI responsive structure for mobile

### PR DESCRIPTION
**Pull request by murad-hubib**
- Added inline label for radio buttons
- Added styles for survey mobile UI
- Created ID for radio buttons

@bradenmacdonald  Please review

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
@murad-hubib Your code looks nice, but I found some issues:

1. On desktop, it break the centre alignment of the radio buttons.

Before:
before
After:
after

2. On desktop, the hitbox for clicking on a radio button is much smaller (too small) due to the removal of the `<label>`. Here you can see how it was / should be:
hitbox

3. Can you provide a screenshot of how it's supposed to look? Here's what I see on mobile, which doesn't look right to me. It looks like I should be able to click anywhere within each large grey rectangle, but if I tap on the area shown in red below, nothing happens and that choice is not selected:
missing hit area

**Comment by murad-hubib** [comment]
@bradenmacdonald Please review this PR as I have covered all the issues you mentioned in your last review.

**Comment by bradenmacdonald** [comment]
:+1: @murad-hubib Thanks!

- [x] I tested this: Tested in apros and LMS
- [x] I read through the code
- [x] I checked for accessibility issues - a11y functionality seems to be preserved
- [ ] ~~Includes documentation~~: n/a

However, these two screens don't seem right to me. I'm not sure what the specs are, but can you please check if these should be improved first?

On this one, the radio buttons are touching the line - I think a bit of padding on the left would look nicer:
screen shot 2017-09-06 at 7 45 04 pm

And here it seems like the numbers should be on the same line:
screen shot 2017-09-06 at 7 45 44 pm

**Comment by murad-hubib** [comment]
@bradenmacdonald Thanks for the review. I believe the screenshots you mentioned are Polls but I didn't work on polls yet. This PR/Ticket is related to surveys only.

**Comment by bradenmacdonald** [comment]
@murad-hubib Ah ok. Feel free to merge then.

**Pull request merged**
