### PR TITLE
[MCKIN-9996]Translation of word "FEEDBACK" updated

### PR DESCRIPTION
**Pull request by musmanmalik**
Translation of word "feedback"  was  wrong in case of Spanish and Portuguese which is updated now.

### CODE REVIEW

**Comment by musmanmalik** [comment]
@xitij2000 I sorry i have to close previous pull request due to some local repo lost. I have created a new one kindly have a look at. Thanks

**Comment by xitij2000** [comment]
@musmanmalik Thanks for the great work. Note that you don't need to have access to the original repo to push to the same branch, you can just clone the repo again, and push to the same branch.

**Comment by musmanmalik** [comment]
@xitij2000  can you please create release tag against this pr as i don't have access to create it.

**Comment by rajheda108** [comment]
Can you please remove me from this email thread?

**Comment by xitij2000** [comment]
@rajheda108 I think you may have subscribed to notifications from this thread (or repository accidentally). The emails you get will have a link to mute the thread.

**Pull request merged**
