### PR TITLE
Add attributes to student_view_data for both Poll and Survey

### PR DESCRIPTION
**Pull request by zamanafzal**

### CODE REVIEW

**Comment by zamanafzal** [comment]
@bradenmacdonald Please have a look into this.
 In this pr, some attributes have been added in student_view_data for survey and poll as of requirements.
student_view_data be like for survey = 
"student_view_data": {
    "feedback": "This is feedback message survey.",
    "private_results": false,
    "max_submissions": 1,
    "block_name": "Block Name",
    ........................
}
student_view_data be like for poll = 
"student_view_data": {
    "feedback": "This is feedback message survey.",
    "private_results": false,
    "max_submissions": 1,
    ........................
}

**Comment by bradenmacdonald** [comment]
@zamanafzal Sure, I'll get someone to review this in the coming week.

**Comment by mtyaka** [comment]
Thanks @zamanafzal!

:+1:

- [x] I tested this: I verified that the new fields are visible in the Course Blocks API.
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ n/a
- [x] Includes documentation

**Comment by zamanafzal** [comment]
@mtyaka Please make the release of this Pr.

**Comment by mtyaka** [comment]
@zamanafzal I'll release the new version together with #40, as soon as it gets merged.

**Comment by mtyaka** [comment]
@zamanafzal https://github.com/open-craft/xblock-poll/releases/tag/v1.5.0 released.

**Pull request merged**
