### PR TITLE
add student_view_data to poll and survey xblock

### PR DESCRIPTION
**Pull request by msaqib52**
This PR add student_view_data to poll and survey xblocks.
@bradenmacdonald could you please review?

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
@msaqib52 This looks good!

However, I believe the mobile view will also want to be able to show the user's previous selection/vote when it loads. To achieve that, you'll need to add an `@XBlock.handler` called `student_view_user_state` which returns `choice` and `tally` (see the Google Doc linked to from MCKIN-5046).

Also, could you please add a test? Something like https://github.com/open-craft/xblock-ooyala/blob/d9208ac456f3fc33b6193b890d81f3dbf98cd211/tests/test_ooyala_player.py#L56-L74

**Comment by msaqib52** [comment]
@bradenmacdonald i have updated this PR with suggestions please have a look.

**Comment by msaqib52** [comment]
@bradenmacdonald Thank you, i have added documentation, Fixed typo, bumped version and squashed commits.

**Comment by bradenmacdonald** [comment]
@msaqib52 Nice! The travis build isn't passing so I just restarted it - maybe it's just a flaky test.

**Comment by bradenmacdonald** [comment]
@msaqib52 Thanks! Merging now :)

**Pull request merged**
