### PR TITLE
MCKIN-18291 Exports results to CSV is not working 

### PR DESCRIPTION
**Pull request by musmanmalik**
https://edx-wiki.atlassian.net/browse/MCKIN-18291

ssue:
edx has recently changed lms.djangoapps.courseware.models.StudentModule from courseware.models.StudentModule to avoid conflict in StudentModule. But MCKA is still using courseware.models.StudentModule and we are getting issue while exporting poll results.

Fix:
I have applied both using try statement in order to get it fix for both cases.

### CODE REVIEW

**Comment by musmanmalik** [comment]
@xitij2000 Please review this.

**Comment by taniwha** [comment]
@musmanmalik I've taken a look (seems good so far) and done some testing. I can confirm that the "download csv" button becomes enabled (and does not when I change the caught exception to ImportError), but the download itself fails due to the output file not existing. Is this a problem in my test environment?

**Comment by musmanmalik** [comment]
@taniwha Thanks for reaching out. The failure of "download csv" is not related to this and we don't have some configuration on local regarding. So this is the expected behaviour you may test with or without these changes the behaviour will be same.

**Comment by taniwha** [comment]
@musmanmalik Ah, great. Thank you.

**Comment by taniwha** [comment]
:+1:

- [x] I tested this: (describe what you tested)
- [x] I read through the code
~~- [ ] I checked for accessibility issues~~
~~- [ ] Includes documentation~~
~~- [ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~~

**Comment by musmanmalik** [comment]
@taniwha Thank you so much Please create a release tag as well.

**Comment by taniwha** [comment]
Oh, thanks for the reminder.

**Pull request merged**
