### PR TITLE
Fix most frequent deprecation warnings

### PR DESCRIPTION
**Pull request by awaisdar001**
Fixed the most frequently occurring deprecation warnings.

```
Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release
``` 
- most of these were due to a single mis-configured resource path with a leading slash.

```
xblock.fragment is deprecated. Please use web_fragments.fragment instead
```

FYI -- @jmbowman, @xitij2000

### CODE REVIEW

**Comment by awaisdar001** [comment]
@xitij2000 Can you please review the PR and merge?

thanks.

**Comment by Agrendalath** [comment]
@awaisdar001, please rebase this on the current `master` branch to fix the failing tests.

**Comment by awaisdar001** [comment]
@Agrendalath I am having hard time rebasing my branch b/c of `poll/public/js/translations` folder contains folder names which are case insensitive. I am on macOs and my git is freaking out.  My Git thinks 
`poll/public/js/translations/zh_CN/textjs.js` and `poll/public/js/translations/zh_cn/textjs.js`are one folder because the names are similar. Can you let me know if there is anyway I can address this?

**Comment by awaisdar001** [comment]
@Agrendalath Please review.

**Comment by Agrendalath** [comment]
@awaisdar001, I'm actually not the reviewer here, just wanted to point the way of fixing tests.
cc: @xitij2000

**Comment by toxinu** [comment]
@awaisdar001 Can you rebase with `master` and update the module version to `1.9.6`?

**Comment by toxinu** [comment]
👍

 - [x] I tested this: check that the xBlock is working properly on devstack
 - [x] I read through the code
 - ~I checked for accessibility issues~
- ~Includes documentation~

**Comment by toxinu** [comment]
Thanks for your contribution @awaisdar001! :)

**Comment by awaisdar001** [comment]
> Thanks for your contribution @awaisdar001! :)
🙌

**Pull request merged**
