### PR TITLE
Fixed StudentModule conflicting path 

### PR DESCRIPTION
**Pull request by AhtishamShahid**
[PROD-1295](https://openedx.atlassian.net/browse/PROD-1295)

Issue:
People were unable to download poll reports due to conflict in StudentModule 

Fix: 
Updated StudentModule path and there was another issue with the concatenation of the list which seems likely was caused due to python update.

### CODE REVIEW

**Comment by Agrendalath** [comment]
@AhtishamShahid, please rebase this on the current `master` branch to fix the failing tests.

**Comment by AhtishamShahid** [comment]
> @AhtishamShahid, please rebase this on the current `master` branch to fix the failing tests.

@Agrendalath I have rebased with master Please review and merge the PR.

**Comment by Agrendalath** [comment]
@AhtishamShahid, I'm actually not the reviewer here, just wanted to point the way of fixing tests.
cc: @xitij2000

**Comment by AhtishamShahid** [comment]
@xitij2000 Please review and merge this PR.

**Comment by toxinu** [comment]
👍

 - [x] I tested this: check that the xBlock is working properly on devstack
 - [x] I read through the code
 - ~I checked for accessibility issues~
- ~Includes documentation~

**Comment by toxinu** [comment]
Thanks for your contribution @AhtishamShahid! 👍

**Pull request merged**
