### PR TITLE
Associate poll options with corresponding question

### PR DESCRIPTION
**Pull request by itsjeyd**
This PR implements [SOL-2081](https://openedx.atlassian.net/browse/SOL-2081); it establishes a programmatic relationship between poll questions and answers that learners can choose from.

**Sandbox URLs**

- Studio: http://studio-pr14085.sandbox.opencraft.hosting/
- LMS: http://pr14085.sandbox.opencraft.hosting/

Latest commit: 14a26a2983614dc97b9a2674adab6187444fe696

**Test instructions**

1. Add a Poll block to a unit in Studio.
2. Navigate to the unit in the LMS.
3. Using a screen reader, verify that the poll question is linked to individual answers.

**Reviewers**

- [x] OpenCraft: @mtyaka 
- [x] edX: @cptvitamin

### CODE REVIEW

**Comment by mtyaka** [comment]
This looks good to me. The only problem I found is that the margin between the question and the radio buttons is too large in Firefox (but it looks fine in Chrome and Safari).

screen shot 2016-12-02 at 08 27 27

After the Firefox issues is addressed, this gets a 👍 from me.

- [x] I tested this: I imported the xblock poll demos into a new course on the sandbox, navigated to one of the Poll blocks in the LMS, verified that the question and radio buttons are grouped together when navigating the page using VoiceOver.
- [x] I read through the code
- [x] I checked for accessibility issues
- [ ] ~~Includes documentation~~ documentation not required

**Comment by itsjeyd** [comment]
Thanks for the review, @mtyaka! I was developing on Chromium; turns out that the user agent stylesheet of that browser modifies the value of the `display` property for `<legend>` elements. I modified the CSS to set the `display` property for `.poll-question` (instead of modifying `margin-bottom`), and I'm getting consistent vertical whitespace now:

**Firefox**

vertical-whitespace-firefox

**Chromium**

vertical-whitespace-chromium

Commit: 6c5416037435cfacede414e5051c3e59783dae5f

I'll update the sandbox shortly.

**Comment by itsjeyd** [comment]
Squashed from 6c5416037435cfacede414e5051c3e59783dae5f.

**Comment by itsjeyd** [comment]
@mtyaka The sandbox is up-to-date if you want to double-check the fix.

**Comment by mtyaka** [comment]
Thanks @itsjeyd, it looks good 👍

**Comment by itsjeyd** [comment]
@mtyaka Thanks!

@cptvitamin This is ready for you to have a look. Sandbox links are in the PR description. Let me know if you have any questions.

**Comment by cptvitamin** [comment]
@itsjeyd this is great!  Thanks for taking care of this detail 👍

**Comment by itsjeyd** [comment]
Thanks for reviewing, @cptvitamin! Merging now.

**Pull request merged**
