### PR TITLE
Add support for django 4.2

### PR DESCRIPTION
**Pull request by irtazaakram**
Hi,

This PR is related to ongoing effort to upgrade openedx to Django 4.2

https://github.com/edx/upgrades/issues/368

Please can we have a new release after this PR is merged.

Thanks,

### CODE REVIEW

**Review by Agrendalath — CHANGES_REQUESTED** [review]
@irtazaakram, Django 4 is never used in these tests. It seems that [this command](https://github.com/open-craft/xblock-poll/blob/68810ca/Makefile#L49-L63) installs `django==3.2.11` directly from the `xblock-sdk` requirements.

**Comment by irtazaakram** [comment]
Hi @Agrendalath,

Thank you for the review. I've made some changes in tox that should install Django 4.2 in test env. Also I've updated package versions in requirements.

Thanks,

**Comment by Agrendalath** [comment]
@irtazaakram, I proposed an alternative approach at https://github.com/open-craft/xblock-poll/pull/108. Would you like to cherry-pick 8d3040b9f4efcdd23ab0177f3d9d32d601a2fc37 into your PR so we can merge it here?

**Comment by irtazaakram** [comment]
Hi @Agrendalath,

I've updated code as per your approach.

Thanks,

**Comment by Agrendalath** [comment]
@irtazaakram, please revert the last commit and **cherry-pick** 8d3040b to ensure all changes are included.

**Comment by irtazaakram** [comment]
@Agrendalath, I've cherry-picked  https://github.com/open-craft/xblock-poll/commit/8d3040b9f4efcdd23ab0177f3d9d32d601a2fc37 into this branch. Please review.

**Review by Agrendalath — APPROVED** [review]
:+1:

* [x] I tested this: checked that the CI is passing
* [x] I read through the code
* [x] I checked for accessibility issues: n/a
* [x] Includes documentation: n/a
* [x] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository: n/a

**Pull request merged**
