### PR TITLE
BB-921 re-order poll xBlock result data

### PR DESCRIPTION
**Pull request by always-boycott-github**

### CODE REVIEW

**Comment by always-boycott-github** [comment]
@xitij2000 no tests were modified but the tests are still green. This specific behavior was therefore not tested and I'm inclined to add a test verifying the tally is no longer ordered by count. Does that sound right to you or should I just verify manually and be done with it?

**Comment by xitij2000** [comment]
@always-boycott-github I guess that's OK since I'm not sure what a test for this would really be testing. 

Could you add a version bump for this? I honestly don't know what this should be. It is a user-facing non-backwards compatible change, so by some logic, it should be a major version bump, but perhaps a minor bump is more in the spirit of the thing?

**Comment by always-boycott-github** [comment]
> perhaps a minor bump is more in the spirit of the thing?

I concur.

**Comment by always-boycott-github** [comment]
bumped & repushed

**Pull request merged**
