### PR TITLE
Added compiled translations

### PR DESCRIPTION
**Pull request by ziafazal**
This PR has compiled translations.
@e-kolpakov could you please merge and create a release(1.2.4)?

### CODE REVIEW

**Comment by e-kolpakov** [comment]
@ziafazal Are you 100% sure we should commit mo files? Since they are generated from po files, I had an impressions (more or less supported [by the docs](http://edx.readthedocs.io/projects/xblock-tutorial/en/latest/edx_platform/edx_lms.html#internationalization-support)) that they should not be committed and generated on "client" instead (as part of launching LMS?)

**Comment by ziafazal** [comment]
@e-kolpakov closing this in favour of #22

**Comment by ziafazal** [comment]
@e-kolpakov reopening this in favour of PR #22

**Comment by e-kolpakov** [comment]
@ziafazal  merged - please delete branch if not used anymore

**Pull request merged**
