### PR TITLE
(WIP) SOL-1824: Extract translated strings procedure's help text updated

### PR DESCRIPTION
**Pull request by malikshahzad228**
Complete README instructions for xblock-poll: [SOL-1824](https://openedx.atlassian.net/browse/SOL-1824)

@asadiqbal08 @mattdrayer FYI

### CODE REVIEW

**Comment by mattdrayer** [comment]
@itsjeyd -- FYI, here is a WIP PR for the follow-on documentation work.

**Comment by itsjeyd** [comment]
@mattdrayer Thanks, great to see this happen so quickly :)

**Comment by OmarIthawi** [comment]
@pomegranited would you mind closing this stray pull request? This repo already have a more streamlined tooling as of #43.

Thank you!

**Comment by pomegranited** [comment]
Sure thing @OmarIthawi !  Thanks for letting us know.

**Pull request closed without merging**
